### ISSUE TITLE
list index out of range error

### ISSUE THREAD

**Issue by MislavSag** [testdrivenio/selenium-grid-docker-swarm#2]
When I try to execute the file, I got an error:

> ---------------------------------------------------------------------------
> IndexError                                Traceback (most recent call last)
> E:\data\Python\selenium-grid-docker-swarm-master\project\script.py in <module>()
>      16 
>      17 if __name__ == '__main__':
> ---> 18     browser = get_driver(sys.argv[2])
>      19     data = run_process(browser, sys.argv[1])
>      20     browser.quit()
> 
> IndexError: list index out of range

**Comment by mjhea0** [comment]
So it's not getting the second arg, `$(docker-machine ip $NODE)`.
